version: "2.1"

services:

  tautulli:
    image: linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/London
    volumes:
      - ./tautulli:/config
    ports:
      - 8181:8181
    restart: unless-stopped

  unifi-controller:
    image: ghcr.io/linuxserver/unifi-controller
    container_name: unifi-controller
    environment:
      - PUID=1001
      - PGID=1001
    volumes:
      - ./unifi/Unifi:/config
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8443:8443
      - 1900:1900/udp
      - 8843:8843
      - 8880:8880
      - 6789:6789
      - 5514:5514
    restart: unless-stopped

  sonarr:
    image: ghcr.io/linuxserver/sonarr:preview
    container_name: sonarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/London
    volumes:
      - ./sonarr:/config
      - /home/usman/NAS/usman_stuff/Media/TV/:/tv
      - /home/usman/NAS/usman_stuff/Media/Downloading/:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped


  radarr1:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr1
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/London
    volumes:
      - ./radarr:/config
      - /home/usman/NAS/usman_stuff/Media/:/movies
      - /home/usman/NAS/usman_stuff/Media/Downloading/:/data
    ports:
      - 7877:7878
    restart: unless-stopped


  radarr4k:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr4k
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/London
    volumes:
      - ./radarr4k:/config
      - /home/usman/NAS/usman_stuff/Media/:/movies
      - /home/usman/NAS/usman_stuff/Media/Downloading/:/data
    ports:
      - 7876:7878
    restart: unless-stopped

  syncthing:
    image: lscr.io/linuxserver/syncthing
    container_name: syncthing
    hostname: syncthing
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/London
    volumes:
      - ./syncthing:/config
      - /home/usman/NAS/BACKUPS/syncthing:/data1
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped

  smokeping:
    image: lscr.io/linuxserver/smokeping
    container_name: smokeping
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./smokeping/config:/config
      - ./smokeping/data:/data
    ports:
      - 89:80
    restart: unless-stopped

  heimdall:
    image: lscr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./heimdall:/config
    ports:
      - 69:80
    restart: unless-stopped